### ISSUE TITLE
Breakage when allowing integers in HashIDs alphabet

### ISSUE THREAD

**Issue by olliebennett** [jcypret/hashid-rails#12]
If configured with integers in the HashIDs alphabet, we have run into various problems resulting from the overridden `find` method.

Basically, certain hashids are created from numbers only (no letters), and it just so happens that those numbers can be correctly "decoded" into a valid integer.

A specific example for us was a Job which is passed the record's ID, and used `find` to retrieve that record. The ID passed in was `197895` but the error returned was `Couldn't find Post with 'id'=70459792`. Notice the completely different ID!

It's too late for us to change our HashID alphabet (it would break all existing IDs), but we can workaround this issue by relying on `find_by_id` (which is not overridden).

I propose this caveat of the system be prominently added to the `README`, as well as defaulting the alphabet to be letters only, to avoid risking this problem for other users.

**Comment by jcypret** [comment]
@olliebennett Ah, that makes a lot of sense. I hadn't run into that issue. I'll put some thought into how best to word that in the Readme. I'll also think through and see if I can come up with any good solution for the present time that doesn't break existing ID's. 

One way would be to try the ID first and see if a record could be found, then if not, decode it as a hashid. However, the would result in an extra database call. Could alternatively check if it's an integer and if so don't try and decode it. The assumption would be that hashids are never going to be just a number, so if it is just a number then assume it's a regular id.

I have some thoughts on how to prevent that for future versions, but it would change existing hashids. Hashids support arrays, so instead of creating a hashid with just the ID, we could store it as an array like `['hashid', 123]`. Then when decoding it, we could ensure the first item in the array is the string "hashid", and if not, know it's not an actual hashid.

**Comment by olliebennett** [comment]
Hey, thanks for the detailed suggestions.

- Agree that the extra database call isn't ideal - not only is there an overhead, but what if that record had been deleted and so was supposed to 404? It still would not be a reliable approach.

- Checking if it's an integer would work perfectly, but as I suggested initially, it relies on the "HashID alphabet" not containing any numbers, or we're back to where we started. The only drawback then is that you can't have full control over the format of your hashids (and I guess removing numbers reduces alphabet size and therefore increases length of hashids more quickly).

- Your array-syntax is also a great idea, however one of the [rules of HashIDs](http://hashids.org/#what-not-to-do) is "Do not encode strings", so it probably couldn't be "hashids" in the first array element.

- Another idea we haven't mentioned is to avoid overriding `find` altogether. This would be a shame as it breaks the "drop-in-replacement" / "it just works" aspect of this project. However, we could manually decode the ID before passing to (the untouched) `find`.

- Adding to the above point, it could be nice, to support a `find_by_hashid` method instead, which should decode the HashID and then call `find`. This should throw `RecordNotFound` exceptions just as `find` does <sup>1</sup>.

Suggestion for adding to README:

> Warning: This gem overrides `find` to accept either a raw ID or a HashID, in order to be a drop-in replacement for your project. This can cause problems when an input is ambiguous, as in the case of a number-only HashID. Therefore, it is recommended that the configured HashIDs "alphabet" should not contain any integers, but be letters only. See [this issue](https://github.com/jcypret/hashid-rails/issues/12) for more information.

<sup>1</sup> In theory, this would also throw "failed to decode hashid" type exceptions too, so not sure how we'd work around that. I guess we'd intercept that and treat as 404 just as we do automatically for `RecordNotFound` or something

**Comment by jcypret** [comment]
I've pushed a new release with the `find_by_hashid` method. This will allow you to force decoding, instead of falling back on the `find` method which could misinterpret the hashid. Raises a 404 RecordNotFound just like the find method when unable to find a record.

Thanks again for the suggestions!
