### ISSUE TITLE
Disable find(hashid)

### ISSUE THREAD

**Issue by taranda** [jcypret/hashid-rails#21]
Is there a way to disable `find(hashid)`?

I have set up a 6 character hashid with [a-z][0-9].  However, if I do a find for a unhashed id (123456), hashid will hash it and return an ActiveRecord::RecordNotFound exception.  

It would be helpful for the find method to either catch the exception and try a non-hashed find or to have a configuration option to disable the `find` method.

**Comment by romanos** [comment]
👍

**Comment by olliebennett** [comment]
Yes, this is a real pain point I've experienced before.

The short-term workaround is to use `find_by_hashid` and `find_by_id` explicitly. Not ideal, but there's no foolproof way around this.

**Comment by taranda** [comment]
(Pull request #22)[https://github.com/jcypret/hashid-rails/pull/22] should resolve this issue.

**Comment by jcypret** [comment]
Thanks everyone for the feedback on this! I'm currently working on an updated version based on past feedback and would be interested to hear any thoughts.

Currently the gem is inherited by all models, so my thoughts for the next version are to allow the functionality to be added on a per-model basis. When included in a model, it would override find (without fallback) to search by hashid. To search by actual ID, you could still use `find_by!(id: 100)`. Options could then be passed in to the model instead of an initializer. 

Additionally, as of Rails 5, there's a base model, so someone wanting to enable to functionality for all models would just need to include the functionality in the base model. This keeps the simplicity of redefining the ID to be a hashid and `find` just working. 

This would also remove the need to warn about alphabet issues. In the newest versions of the base hashid gem, there are checks in place to ensure the alphabet is valid and has a minimum number of unique characters.

**Comment by jcypret** [comment]
In the short-term, I'm happy to merge in this pull request. Should resolve the issues you are talking about. The code looks good aside for a few linter issues, so once those are resolved I can push a new version of the gem.

**Comment by taranda** [comment]
Thanks.  The pull request should be clean now.  Thanks!

**Comment by olliebennett** [comment]
> This would also remove the need to warn about alphabet issues.

@jcypret I think you should definitely warn about alphabet issues; it's a real pain that our system has potentially interchangeable numeric and alpha-numeric IDs and you can't tell (for sure) just by looking at an ID which type it is.

Also, be careful if you're defaulting `find` to use `hashid` automatically. Please consider, for example, how [ActiveRecord::Persistence.reload](http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-reload) works... (the code shows it runs `find(id)`.

**Comment by jcypret** [comment]
Thanks for the feedback @olliebennett !

I'll keep the alphabet warning in mind to make sure developers understand what could happen. 

For the finder method, would you prefer to see something like friendly id has, where you use `User.hashid.find(params[:id])` instead of overriding the default `find` method? I was originally trying to keep it as simple as possible, but that's definitely been the biggest pain point.

**Comment by jcypret** [comment]
@taranda @olliebennett Release the new version of the gem (0.7.0) 👍
